name: test-workflow
on:
  workflow_dispatch:
    inputs:
      env-to-deploy:
        description: The Env Name
        required: true
        type: string
jobs:
  test-flow:
    runs-on: ubuntu-latest
    steps:
      - name: st-1
        run: |
          echo "Step 1"
      - name: st-2
        run: | 
          echo "Step 2"
  pause-flow:
    runs-on: ubuntu-latest
    environment: ${{inputs.env-to-deploy}}
    steps:
      - name: st-3
        run: | 
          echo "Step 3"
