name: Main Token-Rotation Workflow
on: workflow_dispatch
jobs:
  workflow-1:
    uses: ./.github/workflows/res.yml
    with:
      USER_NAME: "atul"
  workflow-2:
    needs: workflow-1
    uses: ./.github/workflows/res2.yml
    with:
      APP_NAME: "at1"
